title: The Twenty Chronicles
description: A docs(learning) site where we'll write about our learnings from the Twenty Project.
theme: just-the-docs

url: https://just-the-docs.github.io

aux_links:
  Template Repository: https://github.com/just-the-docs/just-the-docs-template
